version: "3.8"

services:
  reth-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mainnet_data:/root/.local/share/reth/mainnet

volumes:
  mainnet_data:
    external: true
